// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get web => FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_API_KEY_WEB'] ?? '',
    appId: '1:571559113831:web:30ebbfa5406298283150c2',
    messagingSenderId: '571559113831',
    projectId: 'examguard-e17e9',
    authDomain: 'examguard-e17e9.firebaseapp.com',
    storageBucket: 'examguard-e17e9.firebasestorage.app',
    measurementId: 'G-XK20M8X59R',
  );

  static FirebaseOptions get android => FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_API_KEY_ANDROID'] ?? '',
    appId: '1:571559113831:android:b619bc2b5a1929913150c2',
    messagingSenderId: '571559113831',
    projectId: 'examguard-e17e9',
    storageBucket: 'examguard-e17e9.firebasestorage.app',
  );

  static FirebaseOptions get ios => FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_API_KEY_IOS'] ?? '',
    appId: '1:571559113831:ios:9e98d593df528af63150c2',
    messagingSenderId: '571559113831',
    projectId: 'examguard-e17e9',
    storageBucket: 'examguard-e17e9.firebasestorage.app',
    iosBundleId: 'com.example.examapp',
  );

  static FirebaseOptions get macos => FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_API_KEY_IOS'] ?? '',
    appId: '1:571559113831:ios:9e98d593df528af63150c2',
    messagingSenderId: '571559113831',
    projectId: 'examguard-e17e9',
    storageBucket: 'examguard-e17e9.firebasestorage.app',
    iosBundleId: 'com.example.examapp',
  );

  static FirebaseOptions get windows => FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_API_KEY_WINDOWS'] ?? '',
    appId: '1:571559113831:web:66176fb34713f4e73150c2',
    messagingSenderId: '571559113831',
    projectId: 'examguard-e17e9',
    authDomain: 'examguard-e17e9.firebaseapp.com',
    storageBucket: 'examguard-e17e9.firebasestorage.app',
    measurementId: 'G-056WC22SR2',
  );
}
